name: Auto Freeze issues

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
  - cron: "0 0 * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  stale:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'AUTO: It has been two weeks since additional info was needed and nothing, if no reply is received for a week, it will be auto-closed.'
          days-before-stale: 14
          days-before-close: 7
          operations-per-run: 50
          stale-issue-label: 'freeze'
          any-of-labels: "help wanted"
          ascending: true
